datasource:
    url: jdbc:hsqldb:mem:dataSource
    username: sa
    password:
---
spring:
  profiles.active: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/tpvDB?&useSSL=false
    username: root
    password: borrego