spring:
   profiles:
      active: local
   banner:
      location: 'classpath:/static/banner.txt'
   cloud:
      gcp:
         proyect-id: ${PROYECT_ID}
         sql:
            database-name: ${DATABASE_NAME}
            instance-connection-name: ${INSTANCE_CONNECTION_NAME}    
   datasource:
      username: ${USERNAME}
      password: ${PASSWORD}
   jpa:
      show-sql: true
      properties:
         dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate:
         ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
   mvc:
      throw-exception-if-no-handler-found: true 
logging:
   level:
      org:
         springframework:
            web: DEBUG
server:
   servlet:
      context-path: '/tpvBackend'
application:
   signUpUrl: '/api/user'
   signInUrl: '/auth/login'
   pagination:
      minElementsPerPage: 1
      maxElementsPerPage: 100
   jwt:
      secret: 'SecretKeyToGenJWTs'
      expirationTime: 100000000
