spring:
   profiles:
      active: local
   banner:
      location: 'classpath:/static/banner.txt'
   cloud:
      gcp:
         proyect-id: seraphic-cocoa-239316
         #credentials:
            #scopes: DEFAULT_SCOPES,https://www.googleapis.com/auth/cloudprint
            #location: 'classpath:/static/keys.json'
         sql:
            database-name: tpvBD
            instance-connection-name: seraphic-cocoa-239316:europe-west1:tpvbd     
   datasource:
      username: root
      password: borrego
   jpa:
      show-sql: true
      properties:
         dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate:
         ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
   mvc:
      throw-exception-if-no-handler-found: true 
logging:
   level:
      org:
         springframework:
            web: DEBUG
server:
   servlet:
      context-path: '/tpvBackend'
application:
   signUpUrl: '/api/user'
   signInUrl: '/auth/login'
   pagination:
      minElementsPerPage: 1
      maxElementsPerPage: 100
   jwt:
      secret: 'SecretKeyToGenJWTs'
      expirationTime: 100000000